"""Add room id

Revision ID: 59a8b2e2a19e
Revises: 8d9ab0c0104e
Create Date: 2024-12-15 19:29:08.354610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59a8b2e2a19e'
down_revision: Union[str, None] = '8d9ab0c0104e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('room_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'room_id')
    # ### end Alembic commands ###
