"""Initial migration

Revision ID: 8d9ab0c0104e
Revises: 
Create Date: 2024-12-15 19:02:30.294193

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from passlib.context import CryptContext

# Password hashing and JWT secret
pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")
def get_password_hash(password):
    return pwd_context.hash(password)

# revision identifiers, used by Alembic.
revision: str = '8d9ab0c0104e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('patient', 'staff', 'admin', name='role'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('waiting', 'active', 'closed', name='chatsessionstatus'), default='waiting'),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('patient_transcript', sa.JSON(), nullable=True),
    sa.Column('staff_transcript', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.create_table('patient_doctor_rel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_doctor_rel_id'), 'patient_doctor_rel', ['id'], unique=False)
    
    ## Populate admin data
    password_hash = get_password_hash('admin@1234')
    op.execute(
        sa.text(f"""
        INSERT INTO users (email, name, password, role)
        VALUES ('admin@nma.test', 'Admin', '{password_hash}', 'admin')
        """)
    )
    
    # ### end Alembic commands ###
    

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_doctor_rel_id'), table_name='patient_doctor_rel')
    op.drop_table('patient_doctor_rel')
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
